---
name: 'Prepare Release'

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  get_next_release_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.next_release.outputs.version }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Get next release version
        id: next_release
        run: |
          echo version=$(bundle exec rake vox:version:next) >> "$GITHUB_OUTPUT"

  prepare_release:
    needs: get_next_release_version
    uses: OpenVoxProject/shared-actions/.github/workflows/prepare_release.yml@main
    with:
      allowed_owner: 'OpenVoxProject'
      version: ${{ needs.get_next_release_version.outputs.version }}
    secrets:
      github_pat: ${{ secrets.OPENVOXBOT_COMMIT_AND_PRS }}
      ssh_private_key: ${{ secrets.OPENVOXBOT_SSH_PRIVATE_KEY }}
